name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: La recette magique
      run: echo "La recette est : $RECETTE_SECRETE"
        env:
          RECETTE_SECRETE: ${{ secrets.RECETTE_SECRETE }}
